const allEditComponents = [
    'position', 'delete', 'duplicate', 'content', 'font-family', 'font-weight', 'font-size', 'color', 'background',
    'link', 'image-url', 'line-height', 'letter-spacing', 'text-transform', 'text-decoration', 'box-shadow',
    'shadow-color', 'opacity', 'height', 'width', 'text-align', 'block-align', 'margin-top', 'margin-bottom',
    'margin-left', 'margin-right', 'padding-top', 'padding-bottom', 'padding-left', 'padding-right',
    'border-radius', 'border-width', 'border-style', 'border-color', 'translate-x', 'translate-y'
];

const blockDefinitions = {
    title: {
        label: 'TÍTULO',
        defaultContent: 'TextView',
        defaultStyles: {
            background: 'transparent',
            color: '#1a202c',
            'font-size': '20px',
            'font-weight': '700',
            'padding-top': '15px',
            'padding-bottom': '15px',
            'padding-left': '15px',
            'padding-right': '15px',
            'margin-top': '10px',
            'margin-bottom': '10px',
            'margin-left': '0px',
            'margin-right': '0px',
            'border-radius': '0px',
            'text-align': 'center',
            'border-width': '0px',
            'border-color': '#000000',
            'border-style': 'solid',
            'line-height': '1.6',
            'letter-spacing': '0px',
            'text-transform': 'none',
            'box-shadow': 'none',
            'opacity': '1',
            'width': '100%',
            'height': 'auto',
            'font-family': 'Roboto',
            'text-decoration': 'none',
            'translate-x': '0px',
            'translate-y': '0px'
        },
        enabledComponents: [
            'position', 'delete', 'duplicate', 'content', 'font-family', 'font-weight', 'font-size', 'color',
            'background', 'line-height', 'letter-spacing', 'text-transform', 'text-decoration', 'box-shadow',
            'shadow-color', 'opacity', 'height', 'width', 'text-align', 'block-align', 'margin-top',
            'margin-bottom', 'margin-left', 'margin-right', 'padding-top', 'padding-bottom', 'padding-left',
            'padding-right', 'border-radius', 'border-width', 'border-style', 'border-color', 'translate-x',
            'translate-y'
        ]
    },
    subtitle: {
        label: 'SUBTÍTULO',
        defaultContent: 'TextView',
        defaultStyles: {
            background: 'transparent',
            color: '#4a5568',
            'font-size': '18px',
            'font-weight': '500',
            'padding-top': '15px',
            'padding-bottom': '15px',
            'padding-left': '15px',
            'padding-right': '15px',
            'margin-top': '10px',
            'margin-bottom': '10px',
            'margin-left': '0px',
            'margin-right': '0px',
            'border-radius': '0px',
            'text-align': 'center',
            'border-width': '0px',
            'border-color': '#000000',
            'border-style': 'solid',
            'line-height': '1.6',
            'letter-spacing': '0px',
            'text-transform': 'none',
            'box-shadow': 'none',
            'opacity': '1',
            'width': '100%',
            'height': 'auto',
            'font-family': 'Roboto',
            'text-decoration': 'none',
            'translate-x': '0px',
            'translate-y': '0px'
        },
        enabledComponents: [
            'position', 'delete', 'duplicate', 'content', 'font-family', 'font-weight', 'font-size', 'color',
            'background', 'line-height', 'letter-spacing', 'text-transform', 'text-decoration', 'box-shadow',
            'shadow-color', 'opacity', 'height', 'width', 'text-align', 'block-align', 'margin-top',
            'margin-bottom', 'margin-left', 'margin-right', 'padding-top', 'padding-bottom', 'padding-left',
            'padding-right', 'border-radius', 'border-width', 'border-style', 'border-color', 'translate-x',
            'translate-y'
        ]
    },
    text: {
        label: 'TEXTO',
        defaultContent: 'TextView',
        defaultStyles: {
            background: 'transparent',
            color: '#2d3748',
            'font-size': '16px',
            'font-weight': '400',
            'padding-top': '15px',
            'padding-bottom': '15px',
            'padding-left': '15px',
            'padding-right': '15px',
            'margin-top': '10px',
            'margin-bottom': '10px',
            'margin-left': '0px',
            'margin-right': '0px',
            'border-radius': '0px',
            'text-align': 'left',
            'border-width': '0px',
            'border-color': '#000000',
            'border-style': 'solid',
            'line-height': '1.6',
            'letter-spacing': '0px',
            'text-transform': 'none',
            'box-shadow': 'none',
            'opacity': '1',
            'width': '100%',
            'height': 'auto',
            'font-family': 'Roboto',
            'text-decoration': 'none',
            'translate-x': '0px',
            'translate-y': '0px'
        },
        enabledComponents: [
            'position', 'delete', 'duplicate', 'content', 'font-family', 'font-weight', 'font-size', 'color',
            'background', 'line-height', 'letter-spacing', 'text-transform', 'text-decoration', 'box-shadow',
            'shadow-color', 'opacity', 'height', 'width', 'text-align', 'block-align', 'margin-top',
            'margin-bottom', 'margin-left', 'margin-right', 'padding-top', 'padding-bottom', 'padding-left',
            'padding-right', 'border-radius', 'border-width', 'border-style', 'border-color', 'translate-x',
            'translate-y'
        ]
    },
    link: {
        label: 'LINK',
        defaultContent: 'LinkView',
        link: true,
        defaultStyles: {
            background: 'transparent',
            color: '#D6B3FF',
            'font-size': '14px',
            'font-weight': '900',
            'padding-top': '5px',
            'padding-bottom': '5px',
            'padding-left': '5px',
            'padding-right': '5px',
            'margin-top': '10px',
            'margin-bottom': '10px',
            'margin-left': '0px',
            'margin-right': '0px',
            'border-radius': '0px',
            'text-align': 'left',
            'border-width': '0px',
            'border-color': '#000000',
            'border-style': 'solid',
            'line-height': '1.6',
            'letter-spacing': '0px',
            'text-transform': 'none',
            'box-shadow': 'none',
            'opacity': '1',
            'width': 'auto',
            'height': 'auto',
            'font-family': 'Roboto',
            'text-decoration': 'underline',
            'link': 'https://',
            'translate-x': '0px',
            'translate-y': '0px'
        },
        enabledComponents: [
            'position', 'delete', 'duplicate', 'content', 'font-family', 'font-weight', 'font-size', 'color',
            'background', 'link', 'line-height', 'letter-spacing', 'text-transform', 'text-decoration',
            'box-shadow', 'shadow-color', 'opacity', 'height', 'width', 'text-align', 'block-align',
            'margin-top', 'margin-bottom', 'margin-left', 'margin-right', 'padding-top', 'padding-bottom',
            'padding-left', 'padding-right', 'border-radius', 'border-width', 'border-style', 'border-color',
            'translate-x', 'translate-y'
        ]
    },
    'button-rounded': {
        label: 'BOTÃO',
        defaultContent: 'Button',
        link: true,
        defaultStyles: {
            background: '#FFFFFF',
            color: '#330066',
            'font-size': '14px',
            'font-weight': '800',
            'padding-top': '12px',
            'padding-bottom': '12px',
            'padding-left': '24px',
            'padding-right': '24px',
            'margin-top': '10px',
            'margin-bottom': '10px',
            'margin-left': 'auto',
            'margin-right': 'auto',
            'border-radius': '50px',
            'text-align': 'center',
            'border-width': '2px',
            'border-color': '#330066',
            'border-style': 'solid',
            'line-height': '1.6',
            'letter-spacing': '0px',
            'text-transform': 'uppercase',
            'box-shadow': '3px 3px 0px 0px #E6CCFF',
            'opacity': '1',
            'width': '300px',
            'height': 'auto',
            'font-family': 'Roboto',
            'text-decoration': 'none',
            'link': 'https://',
            'translate-x': '0px',
            'translate-y': '0px'
        },
        enabledComponents: [
            'position', 'delete', 'duplicate', 'content', 'font-family', 'font-weight', 'font-size', 'color',
            'background', 'link', 'line-height', 'letter-spacing', 'text-transform', 'text-decoration',
            'box-shadow', 'shadow-color', 'opacity', 'height', 'width', 'text-align', 'block-align',
            'margin-top', 'margin-bottom', 'margin-left', 'margin-right', 'padding-top', 'padding-bottom',
            'padding-left', 'padding-right', 'border-radius', 'border-width', 'border-style', 'border-color',
            'translate-x', 'translate-y'
        ]
    },
    image: {
        label: 'IMAGEM',
        defaultContent: '',
        defaultStyles: {
            'background-image': '',
            'background-size': 'cover',
            'background-position': 'center',
            'background-repeat': 'no-repeat',
            'padding-top': '0px',
            'padding-bottom': '0px',
            'padding-left': '0px',
            'padding-right': '0px',
            'margin-top': '10px',
            'margin-bottom': '10px',
            'margin-left': '0px',
            'margin-right': '0px',
            'border-radius': '0px',
            'border-width': '2px',
            'border-color': '#000000',
            'border-style': 'solid',
            'box-shadow': '5px 5px 0px 0px #D6B3FF',
            'opacity': '1',
            'width': '100%',
            'height': '200px',
            'translate-x': '0px',
            'translate-y': '0px'
        },
        enabledComponents: [
            'position', 'delete', 'duplicate', 'image-url', 'box-shadow', 'shadow-color', 'opacity', 'height',
            'width', 'block-align', 'margin-top', 'margin-bottom', 'margin-left', 'margin-right',
            'padding-top', 'padding-bottom', 'padding-left', 'padding-right', 'border-radius',
            'border-width', 'border-style', 'border-color', 'translate-x', 'translate-y'
        ]
    },
    'image-grid': {
        label: 'IMAGEM QUADRICULAR',
        defaultContent: '',
        defaultStyles: {
            'background-image': '',
            'background-size': 'cover',
            'background-position': 'center',
            'background-repeat': 'no-repeat',
            'padding-top': '0px',
            'padding-bottom': '0px',
            'padding-left': '0px',
            'padding-right': '0px',
            'margin-top': '10px',
            'margin-bottom': '10px',
            'margin-left': '0px',
            'margin-right': '0px',
            'border-radius': '0px',
            'border-width': '2px',
            'border-color': '#000000',
            'border-style': 'solid',
            'box-shadow': '5px 5px 0px 0px #D6B3FF',
            'opacity': '1',
            'width': '180px',
            'height': '180px',
            'translate-x': '0px',
            'translate-y': '0px'
        },
        enabledComponents: [
            'position', 'delete', 'duplicate', 'image-url', 'box-shadow', 'shadow-color', 'opacity', 'height',
            'width', 'block-align', 'margin-top', 'margin-bottom', 'margin-left', 'margin-right',
            'padding-top', 'padding-bottom', 'padding-left', 'padding-right', 'border-radius',
            'border-width', 'border-style', 'border-color', 'translate-x', 'translate-y'
        ]
    },
    'image-circular': {
        label: 'IMAGEM CIRCULAR',
        defaultContent: '',
        defaultStyles: {
            'background-image': '',
            'background-size': 'cover',
            'background-position': 'center',
            'background-repeat': 'no-repeat',
            'padding-top': '0px',
            'padding-bottom': '0px',
            'padding-left': '0px',
            'padding-right': '0px',
            'margin-top': '10px',
            'margin-bottom': '10px',
            'margin-left': 'auto',
            'margin-right': 'auto',
            'border-radius': '50%',
            'border-width': '2px',
            'border-color': '#000000',
            'border-style': 'solid',
            'box-shadow': '5px 5px 0px 0px #D6B3FF',
            'opacity': '1',
            'width': '150px',
            'height': '150px',
            'translate-x': '0px',
            'translate-y': '0px'
        },
        enabledComponents: [
            'position', 'delete', 'duplicate', 'image-url', 'box-shadow', 'shadow-color', 'opacity', 'height',
            'width', 'block-align', 'margin-top', 'margin-bottom', 'margin-left', 'margin-right',
            'padding-top', 'padding-bottom', 'padding-left', 'padding-right', 'border-width',
            'border-style', 'border-color', 'translate-x', 'translate-y'
        ]
    },
    divider: {
        label: 'DIVISOR',
        defaultContent: '',
        defaultStyles: {
            background: '#000000',
            'padding-top': '0px',
            'padding-bottom': '0px',
            'padding-left': '0px',
            'padding-right': '0px',
            'margin-top': '10px',
            'margin-bottom': '10px',
            'margin-left': '0px',
            'margin-right': '0px',
            'border-radius': '0px',
            'border-width': '0px',
            'border-color': '#000000',
            'border-style': 'solid',
            'box-shadow': 'none',
            'opacity': '1',
            'width': '100%',
            'height': '1px',
            'translate-x': '0px',
            'translate-y': '0px'
        },
        enabledComponents: [
            'position', 'delete', 'duplicate', 'background', 'opacity', 'width', 'height', 'block-align',
            'margin-top', 'margin-bottom', 'margin-left', 'margin-right', 'translate-x', 'translate-y'
        ]
    },
    spacing: {
        label: 'ESPAÇO',
        defaultContent: '',
        defaultStyles: {
            background: 'transparent',
            'padding-top': '0px',
            'padding-bottom': '0px',
            'padding-left': '0px',
            'padding-right': '0px',
            'margin-top': '0px',
            'margin-bottom': '0px',
            'margin-left': '0px',
            'margin-right': '0px',
            'border-radius': '0px',
            'border-width': '0px',
            'border-color': '#000000',
            'border-style': 'solid',
            'box-shadow': 'none',
            'opacity': '1',
            'width': '100%',
            'height': '20px',
            'translate-x': '0px',
            'translate-y': '0px'
        },
        enabledComponents: [
            'position', 'delete', 'duplicate', 'height', 'translate-x', 'translate-y'
        ]
    }
};

function getBlockConfig(type) {
    return blockDefinitions[type] || {};
}

function getEnabledComponents(type) {
    return blockDefinitions[type]?.enabledComponents || [];
}